<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ColorManage.aspx.cs" Inherits="ColorSystem.ColorManage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style>
        .content{
            width:1000px;
            margin:70px auto;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="content">
            <asp:GridView ID="ColorViews" runat="server" AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" GridLines="None" style="text-align:center;" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ColorId" OnRowCancelingEdit="ColorViews_RowCancelingEdit" OnRowDeleting="ColorViews_RowDeleting" OnRowEditing="ColorViews_RowEditing" OnRowUpdating="ColorViews_RowUpdating">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:TemplateField HeaderText="颜色编码">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextColorCode" runat="server" Text='<%# Bind("ColorCode") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Bind("ColorCode") %>'></asp:Label>
                        </ItemTemplate>
                        <ItemStyle Width="120px" />
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="颜色名称">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextName" runat="server" Text='<%# Bind("Name") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Bind("Name") %>'></asp:Label>
                        </ItemTemplate>
                        <ItemStyle Width="130px" />
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="颜色配色">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextMatch" runat="server" Text='<%# Bind("Matching") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("Matching") %>'></asp:Label>
                        </ItemTemplate>
                        <ItemStyle Width="150px" />
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
        </div>
    </form>
</body>
</html>
